### ISSUE TITLE
Radio inputs?

### ISSUE THREAD

**Issue by sharpmachine** [launchscout/angular-schema-form#9]
Hey there,

Great stuff here but seems unfinished.  How the balls do I create a radio input?

**Comment by jibiabraham** [comment]
Hey there, there's a demo page at http://gaslight.github.io/angular-schema-form/. Straight from the demo 

```
{"good": { "type": "boolean", "title": "Good?"}
```

A type `boolean` is what you're looking for

**Comment by sharpmachine** [comment]
Thanks Jibi.

That example is for a checkbox though.  I'm wondering how am I meant to format a question with several answers as a radio group like this:

What's your favorite fruit?
- Apples
- Bananas
- Managos

Also, I noticed the templates are coming from the HTML files, but from the JS file.  How can I make it so they are using the HTML files?
